version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "alembic upgrade head && python main.py"
    ports:
      - 8000:8000
    image: myweb
    hostname: myweb
    container_name: myweb
    env_file:
      - .env