"""game.title increase to 50

Revision ID: 0871fe011704
Revises: a013998f2d74
Create Date: 2023-01-20 12:10:12.332268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0871fe011704'
down_revision = 'a013998f2d74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'cart', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'user_games', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_games', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_table('games')
    # ### end Alembic commands ###
