"""add date to review table

Revision ID: 61b34f449d9c
Revises: a2d1a9687b91
Create Date: 2023-01-28 11:29:42.799615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b34f449d9c'
down_revision = 'a2d1a9687b91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('date_of_create', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('date_of_change', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'date_of_change')
    op.drop_column('reviews', 'date_of_create')
    # ### end Alembic commands ###
