"""added games.user_id

Revision ID: 89065dc8cf5b
Revises: cc04839e88cd
Create Date: 2023-01-20 15:31:50.171011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89065dc8cf5b'
down_revision = 'cc04839e88cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'user_id')
    # ### end Alembic commands ###
